<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
            array('name' => 'United States'),
            array('name' => 'Canada'),
            array('name' => 'Afghanistan'),
            array('name' => 'Albania'),
            array('name' => 'Australia'),
            array('name' => 'Austria'),
            array('name' => 'Azerbaijan'),
            array('name' => 'Belarus'),
            array('name' => 'Belgium'),
            array('name' => 'Brazil'),
            array('name' => 'China'),
            array('name' => 'Czech Republic'),
            array('name' => 'France'),
            array('name' => 'Germany'),
            array('name' => 'Hungary'),
            array('name' => 'Iceland'),
            array('name' => 'India'),
            array('name' => 'Iran (Islamic Republic of)'),
            array('name' => 'Iraq'),
            array('name' => 'Italy'),
            array('name' => 'Jamaica'),
            array('name' => 'Japan'),
            array('name' => 'Kazakhstan'),
            array('name' => 'Kenya'),
            array('name' => 'Korea, Democratic People\'s Republic of'),
            array('name' => 'Kyrgyzstan'),
            array('name' => 'Mexico'),
            array('name' => 'Micronesia, Federated States of'),
            array('name' => 'Moldova, Republic of'),
            array('name' => 'Monaco'),
            array('name' => 'Mongolia'),
            array('name' => 'Montserrat'),
            array('name' => 'Morocco'),
            array('name' => 'Mozambique'),
            array('name' => 'Myanmar'),
            array('name' => 'Namibia'),
            array('name' => 'Nauru'),
            array('name' => 'Nepal'),
            array('name' => 'Netherlands'),
            array('name' => 'Netherlands Antilles'),
            array('name' => 'New Caledonia'),
            array('name' => 'New Zealand'),
            array('name' => 'Nicaragua'),
            array('name' => 'Niger'),
            array('name' => 'Nigeria'),
            array('name' => 'Niue'),
            array('name' => 'Norfork Island'),
            array('name' => 'Northern Mariana Islands'),
            array('name' => 'Norway'),
            array('name' => 'Oman'),
            array('name' => 'Pakistan'),
            array('name' => 'Palau'),
            array('name' => 'Panama'),
            array('name' => 'Papua New Guinea'),
            array('name' => 'Paraguay'),
            array('name' => 'Peru'),
            array('name' => 'Philippines'),
            array('name' => 'Pitcairn'),
            array('name' => 'Poland'),
            array('name' => 'Portugal'),
            array('name' => 'Puerto Rico'),
            array('name' => 'Qatar'),
            array('name' => 'Republic of South Sudan'),
            array('name' => 'Reunion'),
            array('name' => 'Romania'),
            array('name' => 'Russian Federation'),
            array('name' => 'Rwanda'),
            array('name' => 'Saint Kitts and Nevis'),
            array('name' => 'Saint Lucia'),
            array('name' => 'Saint Vincent and the Grenadines'),
            array('name' => 'Samoa'),
            array('name' => 'San Marino'),
            array('name' => 'Sao Tome and Principe'),
            array('name' => 'Saudi Arabia'),
            array('name' => 'Senegal'),
            array('name' => 'Serbia'),
            array('name' => 'Seychelles'),
            array('name' => 'Sierra Leone'),
            array('name' => 'Singapore'),
            array('name' => 'Slovakia'),
            array('name' => 'Slovenia'),
            array('name' => 'Solomon Islands'),
            array('name' => 'Somalia'),
            array('name' => 'South Africa'),
            array('name' => 'South Georgia South Sandwich Islands'),
            array('name' => 'Spain'),
            array('name' => 'Sri Lanka'),
            array('name' => 'St. Helena'),
            array('name' => 'St. Pierre and Miquelon'),
            array('name' => 'Sudan'),
            array('name' => 'Suriname'),
            array('name' => 'Svalbarn and Jan Mayen Islands'),
            array('name' => 'Swaziland'),
            array('name' => 'Sweden'),
            array('name' => 'Switzerland'),
            array('name' => 'Syrian Arab Republic'),
            array('name' => 'Taiwan'),
            array('name' => 'Tajikistan'),
            array('name' => 'Tanzania, United Republic of'),
            array('name' => 'Thailand'),
            array('name' => 'Togo'),
            array('name' => 'Tokelau'),
            array('name' => 'Tonga'),
            array('name' => 'Trinidad and Tobago'),
            array('name' => 'Tunisia'),
            array('name' => 'Turkey'),
            array('name' => 'Turkmenistan'),
            array('name' => 'Turks and Caicos Islands'),
            array('name' => 'Tuvalu'),
            array('name' => 'Uganda'),
            array('name' => 'Ukraine'),
            array('name' => 'United Arab Emirates'),
            array('name' => 'United Kingdom'),
            array('name' => 'United States minor outlying islands'),
            array('name' => 'Uruguay'),
            array('name' => 'Uzbekistan'),
            array('name' => 'Vanuatu'),
            array('name' => 'Vatican City State'),
            array('name' => 'Venezuela'),
            array('name' => 'Vietnam'),
            array('name' => 'Virgin Islands (British)'),
            array('name' => 'Virgin Islands (U.S.)'),
            array('name' => 'Wallis and Futuna Islands'),
            array('name' => 'Western Sahara'),
            array('name' => 'Yemen'),
            array('name' => 'Yugoslavia'),
            array('name' => 'Zaire'),
            array('name' => 'Zambia'),
            array('name' => 'Zimbabwe'),
        );
        DB::table('countries')->insert($countries);
    }
}
